export const resOffers = {
  relations: [
    'item',
    'item.owner',
    'user',
    'user.wihses',
    'user.wihses.owner',
    'user.wihses.offers',
    'user.offers',
    'user.offers.user',
    'user.wishlist',
    'user.wishlist.owner',
    'user.wishlist.items',
  ],
  select: {
    id: true,
    createdAt: true,
    updatedAt: true,
    item: {
      id: true,
      createdAt: true,
      updatedAt: true,
      name: true,
      link: true,
      image: true,
      price: true,
      raised: true,
      copied: true,
      description: true,
      owner: {
        id: true,
        username: true,
        about: true,
        avatar: true,
        createdAt: true,
        updatedAt: true,
      },
      offers: true,
    },
    amount: true,
    hidden: true,
    user: {
      id: true,
      username: true,
      about: true,
      avatar: true,
      createdAt: true,
      updatedAt: true,
      email: true,
      wihses: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        link: true,
        image: true,
        price: true,
        raised: true,
        copied: true,
        description: true,
        owner: {
          id: true,
          username: true,
          about: true,
          avatar: true,
          createdAt: true,
          updatedAt: true,
        },
        offers: true,
      },
      offers: {
        id: true,
        createdAt: true,
        updatedAt: true,
        user: {
          id: true,
          username: true,
          about: true,
          avatar: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      wishlist: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        image: true,
        owner: {
          id: true,
          username: true,
          about: true,
          avatar: true,
          createdAt: true,
          updatedAt: true,
        },
        items: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          link: true,
          image: true,
          price: true,
          raised: true,
          copied: true,
          description: true,
        },
      },
    },
  },
};

export const resUser = {
  id: true,
  username: true,
  about: true,
  avatar: true,
  createdAt: true,
  updatedAt: true,
};
